# Generated by Django 6.0.3 on 2026-04-25 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Quản lý'), ('waiter', 'Phục vụ'), ('chef', 'Bếp trưởng'), ('cashier', 'Thu ngân'), ('bartender', 'Pha chế')], max_length=20, verbose_name='Chức vụ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương (VNĐ)')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày vào làm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
            },
        ),
    ]
