# Generated by Django 6.0.3 on 2026-04-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục món ăn',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nguyên liệu')),
                ('quantity', models.FloatField(default=0, verbose_name='Số lượng tồn kho')),
                ('unit', models.CharField(max_length=20, verbose_name='Đơn vị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.FloatField(default=1, verbose_name='Số lượng cần')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ingredient', verbose_name='Nguyên liệu')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên món')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá (VNĐ)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Hình ảnh')),
                ('status', models.CharField(choices=[('available', 'Còn hàng'), ('unavailable', 'Hết hàng'), ('seasonal', 'Theo mùa')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Món nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category', verbose_name='Danh mục')),
                ('ingredients', models.ManyToManyField(related_name='menu_items', through='catalog.Inventory', to='catalog.ingredient', verbose_name='Nguyên liệu')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Thực đơn',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.menuitem', verbose_name='Món ăn'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('menu_item', 'ingredient')},
        ),
    ]
