# Generated by Django 6.0.3 on 2026-04-25 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Số bàn')),
                ('capacity', models.IntegerField(default=4, verbose_name='Sức chứa')),
                ('status', models.CharField(choices=[('available', 'Trống'), ('occupied', 'Đang dùng'), ('reserved', 'Đã đặt'), ('cleaning', 'Đang dọn')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('zone', models.CharField(choices=[('indoor', 'Trong nhà'), ('outdoor', 'Ngoài trời'), ('vip', 'VIP'), ('bar', 'Quầy bar')], default='indoor', max_length=20, verbose_name='Khu vực')),
            ],
            options={
                'verbose_name': 'Bàn',
                'verbose_name_plural': 'Quản lý bàn',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Đang phục vụ'), ('pending_payment', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã huỷ')], default='open', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ ngân hàng'), ('transfer', 'Chuyển khoản'), ('momo', 'MoMo'), ('vnpay', 'VNPay')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giảm giá (%)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer', verbose_name='Khách hàng')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phục vụ')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='operations.table', verbose_name='Bàn')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá')),
                ('status', models.CharField(choices=[('pending', 'Chờ chế biến'), ('preparing', 'Đang làm'), ('ready', 'Sẵn sàng'), ('served', 'Đã phục vụ'), ('cancelled', 'Đã huỷ')], default='pending', max_length=20, verbose_name='Trạng thái bếp')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.menuitem', verbose_name='Món ăn')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.IntegerField(verbose_name='Số người')),
                ('reservation_date', models.DateField(verbose_name='Ngày đặt')),
                ('reservation_time', models.TimeField(verbose_name='Giờ đặt')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('arrived', 'Đã đến'), ('cancelled', 'Đã huỷ'), ('no_show', 'Không đến')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên tạo')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='customers.customer', verbose_name='Khách hàng')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='operations.table', verbose_name='Bàn')),
            ],
            options={
                'verbose_name': 'Đặt bàn',
                'verbose_name_plural': 'Quản lý đặt bàn',
                'ordering': ['-reservation_date', 'reservation_time'],
            },
        ),
    ]
